using System;
using System.IO;
using System.Linq;
using System.Security;
using System.Text;
using System.Threading;
using System.Windows;
using System.Windows.Threading;
using AnyListen.Notification.WindowMessages;
using AnyListen.Settings;
using AnyListen.Settings.RegistryManager;
using AnyListen.Setting